### PR TITLE
fix: reduced the complexity of validate-schema.js

### LINKED ISSUE #482: Reduce cognitive complexity in `validate-schemas.js`
- While the development of #452, there were complaints about [cognitive complexity by SonarCloud](https://sonarcloud.io/project/issues?id=asyncapi_asyncapi-node&pullRequest=452&resolved=false&inNewCodePeriod=true)

- We have to address this issue by simplifying the script.

### PR DESCRIPTION
**Pull request by Min2who**
fixes #482

### CODE REVIEW

File: scripts/validate-schemas.js [hunk 1]
```diff
@@ -1,90 +1,60 @@
...
+function validateSchema(filePath, fileContent, schemaValidator) {
+  try {
+    const obj = JSON.parse(fileContent);
+    const validate = schemaValidator(obj);
 
-    const files = fs.readdirSync(directoryPath);
+    if (validate) {
+      console.log(`\n${filePath}: JSON Schema is valid!`);
+    } else {
+      console.error(`\n${filePath}: JSON Schema is not valid:`, schemaValidator.errors);
```
Comment (smoya) [inline scripts/validate-schemas.js:16]: We are already printing errors at the end of the execution. I think we can remove this log line.

File: scripts/validate-schemas.js [hunk 2]
```diff
@@ -1,90 +1,60 @@
...
-
-  try{
+function validateSchema(filePath, fileContent, schemaValidator) {
+  try {
+    const obj = JSON.parse(fileContent);
+    const validate = schemaValidator(obj);
 
-    const files = fs.readdirSync(directoryPath);
+    if (validate) {
+      console.log(`\n${filePath}: JSON Schema is valid!`);
```
Comment (smoya) [inline scripts/validate-schemas.js:14]: Very nitpick, feel free to skip:

I believe this is responsibility of the caller (validate function) rather than to this func. You can just return validation result, then the caller should act accordingly.

File: scripts/validate-schemas.js [hunk 3]
```diff
@@ -1,90 +1,60 @@
...
-                    file,
-                    errors: obj.$schema === 'http://json-schema.org/draft-04/schema'
-                    ? ajvDraft04.errors
-                    : ajv.errors
-                });
-            }
-        } catch (error) {
-            validationErrors.push({
-            file,
-            errors: [{ message: `\nError reading or parsing JSON Schema: ${error.message}` }]
```
Comment (smoya) [inline scripts/validate-schemas.js:64]: We are missing this crucial part; the collection of errors

File: scripts/validate-schemas.js [hunk 4]
```diff
@@ -1,90 +1,60 @@
...
+      const schemaValidator = (obj) => {
+        return (obj.$schema === 'http://json-schema.org/draft-04/schema') ? ajvDraft04.validateSchema(obj) : ajv.validateSchema(obj);
+      };
 
-            // Print errors after processing all files
-        validationErrors.forEach(({ file, errors }) => {
-            console.error(`\n${file}: JSON Schema is not valid:`, errors);
-        });
+      if (!validateSchema(filePath, fs.readFileSync(filePath, 'utf8'), schemaValidator)) {
+        validationErrors.push({ file });
```
Comment (smoya) [inline scripts/validate-schemas.js:43]: You are skipping a very important part: the collection of the errors. It was here https://github.com/asyncapi/spec-json-schemas/pull/483#discussion_r1451383397

**Review by smoya — CHANGES_REQUESTED** [review]

**Comment by Min2who** [comment]
can yu review it
cc @smoya @AnimeshKumar923

File: scripts/validate-schemas.js [hunk 5]
```diff
@@ -1,90 +1,71 @@
...
+  } catch (error) {
+    console.error('\nError during validation:', error.message);
+    process.exit(1);
+  }
 }
 
-
-const excludedFiles=['2.0.0-rc1.json', '2.0.0-rc1-without-$id.json']; // added temporarily to avoid validation failure due to these two files. The schemas version are incorrect in these and needs to be fixed.
-
+const excludedFiles = ['2.0.0-rc1.json', '2.0.0-rc1-without-$id.json'];
```
Comment (AnimeshKumar923) [inline scripts/validate-schemas.js:69]: please keep the comment for future reference to other people who may see/modify the code

Comment (Min2who) [reply scripts/validate-schemas.js]: Done @AnimeshKumar923

**Comment by AnimeshKumar923** [comment]
@smoya bringing your kind attention to this. Please have a look...

**Comment by smoya** [comment]
Will review ASAP once i come back from holidays (this monday).

File: scripts/validate-schemas.js (hunk 3 above)
Comment (AnimeshKumar923) [reply scripts/validate-schemas.js:64]: > We are missing this crucial part; the collection of errors

@Min2who has this been implemented/discussed?

**Review by smoya — APPROVED** [review]
LGTM! Thanks for your contribution!
